name         'chrisboulton-php5'
version      '0.0.1'
license      'MIT'
summary      'Install and manage PHP'
author       'Chris Boulton <chris@chrisboulton.com>'
source       'https://github.com/chrisboulton/puppet-php5'
project_page 'https://github.com/chrisboulton/puppet-php5'
